// All-in-one Legal Decipher System
const TERMS=[{id:"person",label:"Person",sources:[{source:"USC",citation:"1 U.S.C. § 1",definition:"Includes individuals and various legal entities.",context:"statutory"},{source:"UCC",citation:"UCC § 1-201",definition:"Covers natural persons and legal/commercial entities.",context:"commercial"}]},{id:"corporation",label:"Corporation",sources:[{source:"USC",citation:"26 U.S.C.",definition:"Artificial entity created by law, separate from shareholders.",context:"statutory"}]},{id:"money",label:"Money",sources:[{source:"UCC",citation:"UCC § 1-201",definition:"Medium of exchange authorized by government.",context:"commercial"}]}];
const CODES=[{id:"usc_1_1",title:"1 U.S.C. § 1",source:"USC",citation:"1 U.S.C. § 1",summary:"General rules of construction including 'person'.",relatedTerms:["person"]}];
const RELATIONS=[{termId:"person",relatedTo:"corporation",label:"Includes artificial entities",type:"commercial"}];

const UI={renderTermList(t){const c=document.getElementById('termList');c.innerHTML='';t.forEach(e=>{const l=document.createElement('li');l.textContent=e.label;l.className='term-item';l.onclick=()=>showTermDetail(e.id);c.appendChild(l)})},renderTermDetail(t,r){const d=document.getElementById('termDetail');if(!t){d.innerHTML='<p>Select a term.</p>';return}const defs=t.sources.map(s=>`<div class="definition-card context-${s.context}"><h4>${s.source} <span class="citation">${s.citation}</span></h4><p>${s.definition}</p><p class="context-label">Context: <strong>${s.context}</strong></p></div>`).join('');const rels=r.map(r=>`<li>${r.type}: <button class="link-btn" onclick="showTermDetail('${r.relatedTo}')">${r.label}</button></li>`).join('')||'<li>No relations.</li>';d.innerHTML=`<h3>${t.label}</h3><section><h4>Definitions</h4><div class="definitions-grid">${defs}</div></section><section><h4>Cross-references</h4><ul class="relations-list">${rels}</ul></section>`},renderCodeList(c){const cont=document.getElementById('codeList');cont.innerHTML='';c.forEach(e=>{const l=document.createElement('li');l.textContent=`${e.source}: ${e.citation}`;l.title=e.title;l.className='code-item';l.onclick=()=>showCodeDetail(e.id);cont.appendChild(l)})},renderCodeDetail(c){const d=document.getElementById('codeDetail');if(!c){d.innerHTML='';return}d.innerHTML=`<h3>${c.title}</h3><p><span class="citation">${c.citation}</span> [${c.source}]</p><p>${c.summary}</p>`}};

function showTermDetail(id){const t=TERMS.find(e=>e.id===id);const r=RELATIONS.filter(e=>e.termId===id);UI.renderTermDetail(t,r)}
function showCodeDetail(id){const c=CODES.find(e=>e.id===id);UI.renderCodeDetail(c)}

function init(){document.getElementById('termSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();const f=TERMS.filter(t=>t.label.toLowerCase().includes(q)||t.id.includes(q));UI.renderTermList(f)});document.getElementById('codeSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();const f=CODES.filter(c=>c.citation.toLowerCase().includes(q)||c.title.toLowerCase().includes(q));UI.renderCodeList(f)});UI.renderTermList(TERMS);UI.renderCodeList(CODES)}

document.addEventListener('DOMContentLoaded',init);
